[ci]
runner = "atlas-nix-trusted"
workspace = true
with_audit = true
with_deny = true
with_docs = true
with_pypi_publish = true
runtime = "nix"
with_nextest = true

[ci.pages]
repo = "caniko/queryfabric"
canonical_domain = "queryfabric.tartanoglu.com"

[release.signing]
key = "818D507F1E62139F8A17EAA64623DEA06FDACFE1"
